export const TEXT_STUBS = {
    text_signUp: "Регистрация",
    text_signIn: "Вход",
    text_createNote: "Создание заметки",
    text_editNote: "Редактирование заметки", 
    text_deleteNote: "Удаление заметки", 
    text_confirmDeletion: "Вы точно хотите удалить эту заметку?", 
    text_add: "Добавить",
    text_saveChanges: "Сохранить изменения",
    text_noteAdded: "Заметка добавлена!",
    text_changesSaved: "Изменения сохранены!",
    text_authorisation_error: "Ошибка авторизации!",
    text_wrongPasswordOrUsername: "Неверно введен логин или пароль.",
    text_notLoggedUser: "Вы не вошли в свой аккаунт.",
    text_failure: "Ошибка!",
    text_failureUserAlreadyExist: "Пользователь с такими данными уже существует!",
    text_success: "Успех!",
    text_successfullAuthorization: "Теперь вы можете просматривать заметки.",
    text_successCreateNewUser: "Вы зарегистрировались."
}